import { signal } from '@angular/core';
import { Timestamp } from 'firebase/firestore';
import { BaseLocation } from '../const/base-location.const';

export interface EventDocument {
  id?: string; // optional because it will be generated by Firestore
  date: Timestamp;
  description: string;
  link: string | null;
  location: EventLocation;
  name: string;
  time: string;
  visible: boolean;
}

export interface EventLocation {
  city: string;
  latitude: number;
  longitude: number;
  state: string;
  street: string;
  venue: string;
}

export class EventFormModel {
  eventForm = signal({
    date: new Date(),
    description: '',
    link: null as string | null,
    location: {
      city: BaseLocation.CITY,
      latitude: BaseLocation.LATITUDE,
      longitude: BaseLocation.LONGITUDE,
      state: BaseLocation.STATE,
      street: BaseLocation.STREET,
      venue: BaseLocation.VENUE,
    },
    name: '',
    time: '',
    visible: true,
  });
}
