import { signal } from '@angular/core';
import { Timestamp } from 'firebase/firestore';

export interface GalleryDocument {
  id?: string; // optional because it will be generated by Firestore
  created: Timestamp;
  depth: number;
  description: string;
  height: number;
  imageUrls: string[];
  name: string;
  storageKey: string;
  style: GalleryStyle;
  visible: boolean;
  weight: number | null;
  width: number;
}

export enum GalleryStyle {
    BRONZE = 'Bronze',
    GLASS = 'Glass',
}

export class GalleryFormModel {
  galleryForm = signal({
    created: new Date(),
    depth: 0,
    description: '',
    height: 0,
    imageUrls: [] as string[],
    name: '',
    storageKey: '',
    style: '',
    visible: true,
    weight: null as number | null,
    width: 0,
  });
}
