import { signal } from '@angular/core';
import { Timestamp } from 'firebase/firestore';

export interface MediaDocument {
  id?: string; // optional because it will be generated by Firestore
  date: Timestamp;
  description: string;
  link: string;
  title: string;
  visible: boolean;
}

export class MediaFormModel {
  mediaForm = signal({
    date: new Date(),
    description: '',
    link: '',
    title: '',
    visible: true,
  });
}
