import { signal } from '@angular/core';

// The gallery's weekly hours: one document in `schedule`. Keys 0–6 are the days of the week,
// Sunday first (as Date.getDay() numbers them). The shape is production's; the legacy site
// reads the collection's first document, so it must not change.
export interface ScheduleDocument {
  id?: string; // optional because it will be generated by Firestore
  0: DayHours;
  1: DayHours;
  2: DayHours;
  3: DayHours;
  4: DayHours;
  5: DayHours;
  6: DayHours;
  specialMessage: string | null;
}

// Times are "HH:mm", as a time input gives them. A closed day keeps its last times.
export interface DayHours {
  open: string;
  close: string;
  isClosed: boolean;
}

export type DayIndex = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const DAY_NAMES = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
] as const;

// The order the week is shown in, Monday first.
export const WEEK_ORDER: readonly DayIndex[] = [1, 2, 3, 4, 5, 6, 0];

export class ScheduleFormModel {
  scheduleForm = signal({
    // One entry per day, in WEEK_ORDER.
    days: WEEK_ORDER.map(() => ({ open: '10:00', close: '18:00', isClosed: false })),
    // A text input's value; saved as null when left blank.
    specialMessage: '',
  });
}
