import { signal } from '@angular/core';
import { Timestamp } from 'firebase/firestore';
import { BaseLocation } from '../const/base-location.const';

export interface StatueDocument {
  id?: string; // optional because it will be generated by Firestore
  dedicated: Timestamp;
  description: string;
  imageUrls: string[];
  location: StatueLocation;
  name: string;
  storageKey: string;
  visible: boolean;
}

export interface StatueLocation {
  city: string;
  latitude: number;
  longitude: number;
  state: string;
  street: string;
  venue: string;
}

export class StatueFormModel {
  statueForm = signal({
    dedicated: new Date(),
    description: '',
    imageUrls: [] as string[],
    location: {
      city: BaseLocation.CITY,
      latitude: BaseLocation.LATITUDE,
      longitude: BaseLocation.LONGITUDE,
      state: BaseLocation.STATE,
      street: BaseLocation.STREET,
      venue: BaseLocation.VENUE,
    },
    name: '',
    storageKey: '',
    visible: true,
  });
}
